list: $/ibsellnet/leadspopupconvertor/models/popups/columns.yaml
modelClass: Ibsellnet\Leadspopupconvertor\Models\Popups
title: Popups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ibsellnet/leadspopupconvertor/popups/update/:id'
